# mysql/templates/mysql-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.fullname" . }}-secret
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
type: Opaque
data:
  # Base64 encoded values. Helm's b64enc function helps with this if passed via values.
  # If you're using a secret management solution, these values might not be directly in values.yaml.
  # For simple local testing, you can pass them via `helm install --set secrets.mysqlRootPassword=...`
  # Or define them here (but don't commit hardcoded sensitive data to git!)
  mysql-root-password: {{ .Values.secrets.mysqlRootPassword | b64enc | quote }}
  mysql-password: {{ .Values.secrets.mysqlPassword | b64enc | quote }}